### ISSUE TITLE
accounts.google.* needs whitlisted from canvas API to pass "browser insecure" warning message

### ISSUE THREAD

**Issue by privacyguy123** [kkapsner/CanvasBlocker#700]
I see other issues popping up mentioning the same things (Google related services) thought I'd drop the fix here.

**Comment by PJW9779** [comment]
I traced my login issues of this week with Google related sites back to CB.
But whitelisting accounts.google.* would defeat the purpose, wouldn't it?

**Comment by privacyguy123** [comment]
It defeats the purpose of what CB is trying to achieve, but if you can't logged in with spoofed data then I think that is a regression ...

**Comment by kkapsner** [comment]
Please try [canvasblocker-beta-1.10.1.20240405.zip](https://github.com/kkapsner/CanvasBlocker/files/14880459/canvasblocker-beta-1.10.1.20240405.zip)

Whitelisting a site where you log in is not a big deal. They already know who you are.

**Comment by PJW9779** [comment]
@kkapsner  :  Eehhmm, not quite. Otherwise they wouldn't have use for a canvas of course.
Anyway, in my FF (124.0.2 (64-bit)) CB add-on (1.10)  there is no option to whitelist a site.

**Comment by privacyguy123** [comment]
I'm certain whitelisting sites has existed since version 0.1 lol

**Comment by PJW9779** [comment]
@privacyguy123 : Really? Good for you!
I just read "Some settings are not always visible."
Explains a lot.

**Comment by privacyguy123** [comment]
Check the little fingerprint icon in the URL bar!

**Comment by privacyguy123** [comment]
Problem seems to extend to also mad lag on Google powered websites, on top of the not being able to log in thing.

**Comment by PJW9779** [comment]
Found the little fingerprint icon in the URL bar,
added accounts.google.* to Whitelist,
saved
flushed FF all (Ctrl/Shiift/Del)
reloaded YT page
login with no issues
👍👍👍

**Comment by kkapsner** [comment]
@PJW9779 and @privacyguy123 : have you tried the beta version mentioned above I should solve the lag and the login problem (no need to whitelist).

**Comment by kkapsner** [comment]
The [current beta version](https://canvasblocker.kkapsner.de/versions/) is my candidate for 1.10.1 - please test it.

**Comment by PJW9779** [comment]
Meaning canvasblocker_beta-1.10.1.20240405.xp - 2024-04-05 08:00 - 432K
Right?

Already using V1.10
My Add-on Manager is set for automatic update, so I haven't noticed the moment of update.
Whitelisted 'accounts.google.*'  yesterday

Right now 'About:addons' gave a "No updates found¨
'Release Notes' gave a "Sorry, but there was an error loading the release notes."

**Test 1 :**
flushed FF all (Ctrl/Shiift/Del)
reloaded YT page
4 seconds lag from clicking 'Sign In' to login boxes.
no lag during login process
lagging response during playing YT clip
not tested switching to other YT clip

**Test 2 :**
flushed FF all (Ctrl/Shiift/Del)
reloaded YT page
no lag from clicking 'Sign In' to login boxes.
no lag during login process
initial lagging response during playing YT clip
not tested switching to other YT clip

**Test 3 :**
flushed FF all (Ctrl/Shiift/Del)
reloaded YT page
15 seconds lag from clicking 'Sign In' to login boxes.
no lag during login process
initial lagging response during playing YT clip
not tested switching to other YT clip

**Test 4 :**
flushed FF all (Ctrl/Shiift/Del)
reloading YT page took 12 seconds
15 seconds lag from clicking 'Sign In' to login boxes.
no lag during login process
10 seconds lagging response starting playing YT clip
10 seconds lagging response switching to other YT clip

**Test 5 :**
flushed FF all (Ctrl/Shiift/Del)
reloading YT page took 12 seconds
20 seconds lag from clicking 'Sign In' to login boxes.
no lag during login process
no lagging response starting playing YT clip
no lagging response switching to other YT clip

**Comment by spodermenpls** [comment]
@PJW9779 Mr. Kapsner means "1.10.1" will be the next release version (on AMO), the latest beta version is "canvasblocker_beta-1.10.20240408" on https://canvasblocker.kkapsner.de/versions/?C=M;O=D , so you should re-run your tests with that one.

**Comment by privacyguy123** [comment]
> The [current beta version](https://canvasblocker.kkapsner.de/versions/) is my candidate for 1.10.1 - please test it.

No, doesn't fix the error. I see considerable slow down on some other page loads like Stackoverflow as well now, unsure if related.

**Comment by kkapsner** [comment]
Please check that you do not have Canvas locker and CanvasBlocker-Beta active at the same time.Am 08.04.2024 10:29 schrieb privacyguy123 ***@***.***>:

The current beta version is my candidate for 1.10.1 - please test it.

No, doesn't fix the error. I see considerable slow down on some other page loads like Stackoverflow as well now, unsure if related.

**Comment by PJW9779** [comment]
@spodermenpls : I'm pretty sure I picked the latest version from the list. But anyway.

Just now clicked and installed 'canvasblocker_beta-1.10.20240408.xpi' via Github-site.
The FF-dashboard then showed "Version 1.10 Last Updated April 5, 2024"

Removed CB and reinstalled from file.
FF-shortcut now showed 'Canvasblocker-Beta'
CB-dashboard now showed "Version .10.20240408 Last Updated April 8, 2024"

I should have investigated the earlier file info more thorough. Guess I'm a bit rusty on reporting.
Based on the latest posts I'll hold testing until further notice.

**Comment by spodermenpls** [comment]
@PJW9779 By what you're describing, it seems like you removed the official, "release channel" addons.mozilla.org-version of CanvasBlocker ("1.10", from April 5th), which wouldn't have been necessary, both versions (beta via canvasblocker.kkapsner.de and release via addons.mozilla.org) can be installed in tandem, just one of them has to be disabled at a time.

**Comment by PJW9779** [comment]
@spodermenpls : Correct, but for testing with clean results it is better to do a clean install.
Of course I _did_ whitelist accounts.google.* again.

Had to restart FF due to a sound issue, so CB was re-enabled.
No lag whatsoever on YT, login or otherwise.
Blisteringly fast.

**Comment by Qhilm** [comment]
I'd be happy to test the beta, but I can't even load canvasblocker.kkapsner.de. It just spins and times out. Is something down?

I still have 1.9 installed from mozilla on my end, just checking: is it 1.10 that is an attempt at fixing the issue or is it 1.10.1-beta ?

**Comment by Qhilm** [comment]
Works for me:
* disabled CanvasBlocker 1.9 (installed from mozilla)
* downloaded and enabled [`canvasblocker_beta-1.10.20240408.xpi`](https://canvasblocker.kkapsner.de/versions/canvasblocker_beta-1.10.20240408.xpi)
* Tested on photos.google.com

Firefox for Mac 124.0.2
macOS 14.4.1

**Comment by spodermenpls** [comment]
@PJW9779 If you want to do testing with a fresh setup, it's a lot easier to create a new profile (in about:profiles) and switch to that temporarily, instead of removing, re-installing and re-adjusting extensions every time in your standard profile.

@Qhilm Mr. Kapsner's website works fine on my end, maybe there's some security measure on @kkapsner 's side that hinders you from accessing?
1.10 was the ill-fated update that was published (after code review by Mozilla) on April 5th, however was rescinded quickly after due to causing severe issues with various websites. 1.10.1 will be the improved and working update for 1.9.

**Comment by PJW9779** [comment]
@spodermenpls : Nah, was a matter of a few seconds. I rarely test extensions. Unless they malfunction, in which case I usually dump them.
In this case I had to drill down to find the culprit. And CB is worth the effort.
Whitelisting accounts.google.* again may be superfluous. Hadn't tested that. I'll give it a try.

**Comment by PJW9779** [comment]
@privacyguy123  : I don't have an account on SO, but logging in using Google was very fast.

**Comment by kkapsner** [comment]
> I am wondering if website slowdown is also CB 

Could be. Please open a new issue for this topic (it's a separate problem) with your exact reproduction scenario.

As the core problem is solved I will close this issue and submit 1.10.1 to AMO.

**Comment by privacyguy123** [comment]
Slowdown was Dark Reader - which happened to update around the same time, disregard.

**Comment by PJW9779** [comment]
Well, DUH!! It didn't register with me but I have the DR add-on installed too. But not turned on, so I missed the impact.
So the lag bug is with DR, so no interaction with CB which earlier did show lag?

**Comment by privacyguy123** [comment]
> Well, DUH!! It didn't register with me but I have the DR add-on installed too. But not turned on, so I missed the impact. So the lag bug is with DR, so no interaction with CB which earlier did show lag?

DR updated again showing bug fixes for lag in release notes, I don't see it on Stackoverflow anymore ... I don't think  it's related to CB at all.
